ARTICLE_DATE_SPAN_CLASS: "date date--mb date--size-3"
HEADLINE_TAG_CLASS: "title pg-title"
ARTICLE_DIV_CLASS: "col-xs-12 col-sm-12 col-md-8 col-lg-8 pull-left bottom-offset content-offset"

CATEGORY_URLS:
  hau: 
    NAJERIYA: https://www.voahausa.com/z/2866/
    BABBAN_TARON: https://www.voahausa.com/z/7357/
    AFIRKA: https://www.voahausa.com/z/2863/
    AMURKA: https://www.voahausa.com/z/5225/
    SAURAN_DUNIYA: https://www.voahausa.com/z/2870/
    KIWON_LAFIYA: https://www.voahausa.com/z/2864/
    SANA_O_I: https://www.voahausa.com/z/6150/
    NISHADI: https://www.voahausa.com/z/5579/
    WASANNI: https://www.voahausa.com/z/2869/
    WORLD_CUP_2022_QATAR: https://www.voahausa.com/z/7275/
    # RAHOTANNIN_LAFIYARMU: https://www.voahausa.com/z/6878/
  swa:
    AFRIKA: https://www.voaswahili.com/z/2774/
    BURUNDI: https://www.voaswahili.com/burundi/
    DUNIA: https://www.voaswahili.com/z/2783/
    IJUMAA: https://www.voaswahili.com/z/4658/
    JAMHURI_YA_KIDEMOKRASIA_YA_KONGO: https://www.voaswahili.com/z/4660/
    KENYA: https://www.voaswahili.com/z/4658/
    MAKALA_MAALUM: https://www.voaswahili.com/z/3141/
    MAREKANI: https://www.voaswahili.com/z/2775/
    RWANDA: https://www.voaswahili.com/z/4768/
    TANZANIA: https://www.voaswahili.com/z/4657/
    UGANDA: https://www.voaswahili.com/z/4659/

